/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  theme: {
    extend: {
      grayscale: {
        10: "10%",
        20: "20%",
        30: "30%",
        40: "40%",
        50: "50%",
        60: "60%",
        70: "70%",
        80: "80%",
        90: "90%",
        100: "100%",
      },
      colors: {
  
        primary: "#481D5C",
        "primary-lite": "#6D4A7D",
        "primary-lite-2": "#DAD2DE",
        "primary-hover": "#8549A1",
        "primary-minab-2": "#321440",
        "primary-dark": "#321440",
        "minab-gray": "#20202A",
        "minab-dark-primary": "#0F0F10",
        
        "header-bg": "#FFFFFF60",
        secondary: "#5A346C",
        "darkmode-white": "#B6A5BE",
        "purple-3": "#6D4A7D",
        icon: "#8549A1",
        "purple-4": "#321440",
        graytext: "#808080",
        "secondary-1": "rgb(229, 229, 229)",
        "secondary-2": "#868686",
        "secondary-3": "#F8F8F8",
        "secondary-4": "#E5E5E5",
        "secondary-5": "#AAAAAA",
        "secondary-6": "#DBDBDB",
        "secondary-7": "#F6F6F6",
        "secondary-8": "#808080",
        "secondary-dark": "#313131",
        "secondary-navbar": "#FFFFFF",
        "secondary-border": "#DAD2DE",
        "minab-dark-header": "#B6A5BE",
        "minab-dark-background": "#20202A",
        "minab-dark-section": "#2C2C38",
        "secondary-dark": "#313131",
        "secondary-navbar": "#FFFFFF",
        "bg-secondary-dark": "#2C2C38",
        "bg-primary-dark": "#20202A",
        "bg-primary": "#DAD2DE",
        "bg-gray": "#E5E5E5",
        "gray-3": "#2C2C38",
        "dark-nav": "#0F0F10",
        // color system for light mode
      },
    },
    fontFamily: {
      body: ["Manrope"],
      display: ["Manrope"],
      sans: ["Manrope"],
      serif: ["Manrope"],
    },
  },
  
  plugins: [],
}

